package org.sess.telegram.bot;

public enum MessageTextKey {
    IN_PROGRESS,
    HELLO_AND_REGISTER,
    HELLO_AND_REGISTER_GEN_NAME,
    HELLO_AND_REGISTER_GET_EMAIL,
    HELLO_AND_REGISTER_GET_EMAIL_AGAIN,
    HELLO_AND_REGISTER_GET_SEX,
    HELLO_AND_REGISTER_GET_BIRTHDAY,
    HELLO_AND_REGISTER_GET_CITY,
    HELLO_AND_REGISTER_GET_CITY_BUTTON,
    HELLO_AND_REGISTER_CHECK,
    SEX_MEN,
    SEX_WOMEN,
    YES,
    NO,
    AGAIN,
    HELLO_AND_REGISTER_OK,
    HELLO_AND_REGISTER_ERROR,
    HELLO_AND_REGISTER_ABORT
}
