---
server:
  port: 18200

spring:
  profiles:
    active: TelegramSourcePoller

telegram:
  bot:
    id:
    template: https://api.telegram.org/bot{botId}/{method}
    poller:
      timeout: 30

geo:
  nominatim:
    url: https://nominatim.openstreetmap.org

logging:
  config: logback.xml